zuul:
  ignoredPatterns: /__portal__/**,
  routes:
    proxy:
      # Must set to empty list as otherwise Set-Cookie etc would be filtered
      sensitiveHeaders:
      path: /**

server.servlet.session.cookie.name: ADMINPROXYPORTALSESSIONID

spring:
  security:
    oauth2:
      client:
        registration:
          oauth-client:
            client-id: ${admin-proxy-portal.oauth.client-id:null}
            client-secret: ${admin-proxy-portal.oauth.client-secret:null}
            redirect-uri-template: "{baseUrl}/__portal__/login/oauth2"
            provider: ${admin-proxy-portal.oauth.provider:google}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.netflix: WARN
    org.springframework.boot.autoconfigure: WARN
    com.netflix: WARN
