zuul:
  ignoredPatterns: /__portal__/**,
  routes:
    proxy:
      path: /**

server.servlet.session.cookie.name: ADMINPROXYPORTALSESSIONID

admin-proxy-portal:
  username: user
  password: pw
  destinations:
    - name: nginx
      url: http://127.0.0.1:8081
      icon: home
    - name: nginx-404
      url: http://127.0.0.1:8081/something
      icon: film

logging:
  level:
    org.springframework.security: WARN
    org.springframework.cloud.netflix: WARN
    com.netflix: WARN
