zuul:
  ignoredPatterns: /__portal__/**,
  routes:
    proxy:
      path: /**

destinations:
  - name: nginx
    url: http://127.0.0.1:8081
    icon: home
  - name: nginx-404
    url: http://127.0.0.1:8081/something
    icon: film

#logging:
#  level:
#    org.springframework.web: DEBUG
